#!/usr/bin/env python     

#####**************************************************************************#####
#Despcription: This program is used to search and delete line with pattern in file.
#Author: Tongyi Dou
#How to use: Just "python replace.py --i run_data.star --o run_data_replace.star"
#Last Edit: 2021-07-11
#####**************************************************************************#####


import re
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--i", dest="input_star", type="string", default="", help="Input .star file generated by RELION [default: %default]")
parser.add_option("--o", dest="output_star", type="string", default="", help="Output .star file [default: %default]")

(options, args) = parser.parse_args()

#Remove all lines that obey with patern
def deleteline(file_i,file_o,pattern)
    file_i_handle = open(file_i, 'r')
    file_i_string = file_i_handle.read()
    file_i_handle.close()
    
    line2 = []
    
    for line in file_i_string:
        search_result = re.search(pattern,line)
        if (! search_result):
          line2.append(line.strip())
    
    file_o_handle = open(file_o, 'w')
    file_o_handle.write(line2)
    file_o_handle.close()

pattern = r'PBD'	
deleteline(options.input_star, options.output_star, pattern)
