#!/usr/bin/env python     

#####**************************************************************************#####
#Despcription: This program is used to search and delete line with pattern in file.
#Author: Tongyi Dou
#How to use: Just "python replace.py --i run_data.star --o run_data_replace.star"
#Last Edit: 2021-07-11
#####**************************************************************************#####


import re
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--i", dest="input_star", type="string", default="", help="Input .star file generated by RELION [default: %default]")
parser.add_option("--o", dest="output_star", type="string", default="", help="Output .star file [default: %default]")

(options, args) = parser.parse_args()

#Remove all lines that obey with patern
def deleteline(file_i,file_o,pattern):
    with open(file_i,"r") as f:
        lines = f.readlines()
    with open(file_o,"w") as f:
        for line in lines:
            if line.strip("\n") != pattern:
                f.write(line)
    
pattern = r'PBD'	
deleteline(options.input_star, options.output_star, pattern)
