#!/usr/bin/env python     

#####**************************************************************************#####
#Despcription: This program is used to search and replace pattern in .star file.
#Author: Tongyi Dou
#How to use: Just "python replace.py --i run_data.star --o run_data_replace.star"
#Last Edit: 2021-07-02
#####**************************************************************************#####


import re
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--input_tlt", dest="input_tlt", type="string", default="", help="Input .tlt file generated by IMOD [default: %default]")
parser.add_option("--input_mdoc", dest="input_mdoc", type="string", default="", help="Input .mdoc file generated by SeiralEM [default: %default]")
parser.add_option("--o", dest="output_order", type="string", default="", help="Output .order file used for RELION subtomogram averaging [default: %default]")

(options, args) = parser.parse_args()

refined_tilt_angle = []
accumulated_dose = []
    
def extract_refined_tilt_angle(file_tlt):
    with open(file_tlt) as file:
        for line in file:
            line = line.rstrip()
            refined_tilt_angle.append(line)
    return refined_tilt_angle
def extract_accumulated_dose(file_mdoc):
    index = 0
    pattern = r'ExposureDose = (\d.\d{*})'
    for line in open(file_mdoc, 'r'):
        line = line.rstrip()
        result = re.search(pattern, line)
        if result and index == 0:
            accumulated_dose.append(result.group(1))
            index += 1
        elif result and index !=0:
            dose = float(accumulated_dose[index-1]) + float(result.group(1))
            accumulated_dose.append(dose)
            index += 1
    return accumulated_dose
def write_order_file(file_order):
    # Write contents to file.
    # Using mode 'w' truncates the file.
    file_order_handle = open(file_order, 'w')
    length1 = len(refined_tilt_angle)
    length2 = len(accumulated_dose)
    print("There are %s refined tilt angles in the input .tlt file." % length1)
    print("There are %s ExposureDose values in the input .mdoc file." % length2)
    for i in range(length1):
        line = str(refined_tilt_angle[i]) + " " + str(accumulated_dose[i])
        file_order_handle.write(line)
    file_order_handle.close()    
   
refined_tilt_angle = extract_refined_tilt_angle(options.input_tlt)
print(refined_tilt_angle)
accumulated_dose = extract_accumulated_dose(options.input_mdoc)
print(accumulated_dose)
write_order_file(options.output_order)

