import re
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--i", dest="input_star", type="string", default="", help="Input .star file generated by RELION [default: %default]")
parser.add_option("--o", dest="output_star", type="string", default="", help="Output .star file [default: %default]")

(options, args) = parser.parse_args()

def replace(file_i, file_o, pattern, subst):
    # Read contents from file as a single string
    file_i_handle = open(file_i, 'r')
    file_i_string = file_i_handle.read()
    file_i_handle.close()

    # Use RE package to allow for replacement (also allowing for (multiline) REGEX)
    file_i_string = (re.sub(pattern, subst, file_i_string))

    # Write contents to file.
    # Using mode 'w' truncates the file.
    file_o_handle = open(file_o, 'w')
    file_o_handle.write(file_i_string)
    file_o_handle.close()

pattern = r'(\d{3})_(\d{2})\.(\d{2})\.(\d{2})\.mrc'				
subst = r'\1_\2_\3_\4.mrc'	

replace(options.input_star, options.output_star, pattern, subst)
