import os
import re
import sys
import fileinput
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--input_star", dest="input_star", type="string", default="", help="Input .star file generated by RELION [default: %default]")
#parser.add_option("--output_star", dest="output_star", type="string", default="", help="Output .star file [default: %default]")

(options, args) = parser.parse_args()

def replaceAll(file,searchExp,replaceExp):
    for line in fileinput.input(file, inplace=1):
        if searchExp in line:
            line = line.replace(searchExp,replaceExp)
        sys.stdout.write(line)

        
pattern = r'(\d{3})_(\d{2})\.(\d{2})\.(\d{2})\.mrc'
replace = r'\1_\2_\3_\4.mrc'
replaceAll(options.input_star,pattern,replace)

import sys
import fileinput

def replaceAll(file,searchExp,replaceExp):
    for line in fileinput.input(file, inplace=1):
        if searchExp in line:
            line = line.replace(searchExp,replaceExp)
        sys.stdout.write(line)
 
pattern = r'(\d{3})_(\d{2})\.(\d{2})\.(\d{2})\.mrc'
replace = r'\1_\2_\3_\4.mrc'
replaceAll(options.input_star,pattern,replace)

import re

def replace(file_i, file_o, pattern, subst):
    # Read contents from file as a single string
    file_i_handle = open(file_i, 'r')
    file_i_string = file_i_handle.read()
    file_i_handle.close()

    # Use RE package to allow for replacement (also allowing for (multiline) REGEX)
    file_o_string = (re.sub(pattern, subst, file_i_string))

    # Write contents to file.
    # Using mode 'w' truncates the file.
    file_o_handle = open(file_o, 'w')
    file_o_handle.write(file_o_string)
    file_o_handle.close()

file_i = "1.star"
file_o = "2.star"
pattern = r'(\d{3})_(\d{2})\.(\d{2})\.(\d{2})\.mrc'				
subst = r'\1_\2_\3_\4.mrc'	

replace(file_i, file_o, pattern, subst)
