import os
import re
import sys
import fileinput
import numpy as np
from optparse import OptionParser

np.set_printoptions(threshold=np.inf)

parser = OptionParser()
parser.add_option("--input_star", dest="input_star", type="string", default="", help="Input .star file generated by RELION [default: %default]")
#parser.add_option("--output_star", dest="output_star", type="string", default="", help="Output .star file [default: %default]")

(options, args) = parser.parse_args()

def replaceAll(file,searchExp,replaceExp):
    for line in fileinput.input(file, inplace=1):
        if searchExp in line:
            line = line.replace(searchExp,replaceExp)
        sys.stdout.write(line)

        
pattern = r'(\d{3})_(\d{2})\.(\d{2})\.(\d{2})\.mrc'
replace = r'\1_\2_\3_\4.mrc'
replaceAll(options.input_star,pattern,replace)
